version: '3.8'

services:
  app:
    build:
      context: ./php
    container_name: laravel_app
    volumes:
      - ./src:/var/www
    working_dir: /var/www
    ports:
      - 9000:9000
    depends_on:
      - db

  web:
    image: nginx:stable
    container_name: nginx_web
    ports:
      - 8080:80
    volumes:
      - ./src:/var/www
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - app

  db:
    image: mysql:8.0
    container_name: mysql_db
    restart: always
    environment:
      MYSQL_DATABASE: laravel
      MYSQL_ROOT_PASSWORD: secret
    ports:
      # - 3306:3306
      - 3307:3306
    volumes:
      - db_data:/var/lib/mysql

volumes:
  db_data:
